CREATE TABLE SENT_SMS(
    FK_USER INTEGER NOT NULL,
    MESSAGE VARCHAR(3000) NOT NULL,
    REQUESTDATE DATETIME NULL,
    RECEIVERS VARCHAR(3000) NOT NULL,
    SEND_DATE DATETIME NULL
);

ALTER TABLE SENT_SMS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);