CREATE TABLE SMS_TO_SEND(
    FK_USER INTEGER NOT NULL,
    MESSAGE VARCHAR(3000) NOT NULL,
    REQUESTDATE DATETIME NULL,
    RECEIVERS VARCHAR(3000) NOT NULL,
    SEND_DATE DATETIME NULL
);

ALTER TABLE SMS_TO_SEND add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);