CREATE TABLE SMS_USERS(
    LOGIN VARCHAR(40) NOT NULL,
	NAME VARCHAR(40) NULL,
	SURNAME VARCHAR(40) NULL,
	EMAIL VARCHAR(40) NULL,
	PASSWORD VARCHAR(40) NOT NULL,
	REGISTERDATE DATETIME NULL,
	PHONE VARCHAR(20) NULL
);

ALTER TABLE SMS_USERS add column ID INTEGER  NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (ID);

